import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/foundation.dart';
import '../models/notification_model.dart';
import '../../../../core/constants/firebase_constants.dart';

class NotificationStorageService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  static const String _collectionName = FirebaseConstants.notifications;

  /// Send a notification to a specific user (Save to Firestore)
  Future<void> sendNotification({
    required String receiverId,
    required String senderId,
    required String senderName,
    String? senderPhotoUrl,
    required NotificationType type,
    required String title,
    required String message,
    Map<String, dynamic>? metadata,
  }) async {
    try {
      final notification = AppNotification(
        id: '', // Generated by Firestore
        receiverId: receiverId,
        senderId: senderId,
        senderName: senderName,
        senderPhotoUrl: senderPhotoUrl,
        type: type,
        title: title,
        message: message,
        timestamp: DateTime.now(),
        metadata: metadata,
      );

      await _firestore.collection(_collectionName).add(notification.toMap());
    } catch (e) {
      // Fallback to print if AppLogger fails or doesn't exist
    }
  }

  /// Get real-time notifications for a user
  Stream<List<AppNotification>> getNotifications(String userId) {
    return _firestore
        .collection(_collectionName)
        .where('receiverId', isEqualTo: userId)
        .orderBy('timestamp', descending: true)
        .limit(50)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs
          .map((doc) => AppNotification.fromMap(doc.data(), doc.id))
          .toList();
    });
  }

  /// Mark a notification as read
  Future<void> markAsRead(String notificationId) async {
    try {
      await _firestore
          .collection(_collectionName)
          .doc(notificationId)
          .update({'isRead': true});
    } catch (e) {
      if (kDebugMode) {
        debugPrint('Error marking notification as read: $e');
      }
    }
  }

  /// Mark all notifications as read for a user
  Future<void> markAllAsRead(String userId) async {
    try {
      final querySnapshot = await _firestore
          .collection(_collectionName)
          .where('receiverId', isEqualTo: userId)
          .where('isRead', isEqualTo: false)
          .get();

      if (querySnapshot.docs.isEmpty) return;

      final batch = _firestore.batch();
      for (var doc in querySnapshot.docs) {
        batch.update(doc.reference, {'isRead': true});
      }
      await batch.commit();
    } catch (e) {
      if (kDebugMode) {
        debugPrint('Error marking all notifications as read: $e');
      }
    }
  }

  /// Delete a notification
  Future<void> deleteNotification(String notificationId) async {
    try {
      await _firestore.collection(_collectionName).doc(notificationId).delete();
    } catch (e) {
      if (kDebugMode) {
        debugPrint('Error deleting notification: $e');
      }
    }
  }
}
